### ISSUE TITLE
[Feature Request] Reequipable swords / shields

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#348] opened 2024-06-02 22:37 UTC
I encountered a bug I cannot seem to reproduce, but I decided to make a suggestion in case other people encounter it.

**Describe the bug**
Link somehow unequipped his sword, and was unable to equip it.

**To Reproduce**
N/A

**Expected behavior**
Link should be able to equip his sword with the A button.

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/2273e513-dc84-44a8-8a20-a8ad16e96a50)
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/9c9babe2-8ccc-485b-ab7a-61db780d80e3)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version: 1.1.1
 - CPU: AMD 5600x
 - GPU: Nvidia RTX 3060
 - GPU driver: Nvidia driver 535.161.08

**Additional context**
I was quickly switching from Goron, to Zora, to Human link with the dpad
 (Note was not cursed by Bubbles)

**Comment by Mr-Wiseguy** [comment] 2024-06-02 22:47
Thanks for the report. There's no way for the sword to be unequipped, so there's no way to add a way to re-equip it. Additionally, using the D-Pad to switch transformations can't remove your sword.

Were you using any glitches during your playthrough, such as entering areas earlier than normal? Riding Epona before getting the bow is known to cause a similar issue to this one.

If that's not the case, then I'd need more info to fix this issue since there's no way to reproduce it currently.

**Comment by ActuallyTheOwner** [comment] 2024-06-08 23:23
I did not have epona unlocked, but I did have the bow.
I used Goron link with bombs to bomb boost into Ikana
The second slot of the save is a backup of the glitch

Edit github does not support the file type
Rename this png into bin[
![mm n64 us 1 0](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/18967189-c490-4a10-8e2c-4cc5eba65eb5)
](url)

**Comment by ActuallyTheOwner** [comment] 2024-06-08 23:26
Sorry, have to reattach the file
I am using a flatpak version of Firefox which prefers the desktop as places to take files from 

[mm.n64.us.1.0.gz](https://github.com/user-attachments/files/15749880/mm.n64.us.1.0.gz)


Rename the end portion from .gz to .bin
Github does not allow uploading .bin for some reason
The png method did not work

edit: I do not have the bow, the bow is on the other file?
I thought I got the bow, but I must have misremembered.
I used action swap on file1 to that I could do stuff with the owls 
Is it related to that?
I don't see how index warp would effect another file.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 04:26
As I mentioned, not having a bow and then doing certain things in the game causes this, it happens in the original game. Since you're making heavy use of glitches in your playthrough, I'm closing this as it's almost certainly the original behavior and fixing that is out of the scope of this project.

**Closed as completed by Mr-Wiseguy** 2024-06-11 04:26 UTC
