### ISSUE TITLE
Xbox controller joystick issues

### ISSUE THREAD

**Issue by SnippyGiraffe** [Mr-Wiseguy/Zelda64Recomp#404] opened 2024-06-18 22:27 UTC
**Describe the bug**
It seems like the program is having issues with the Xbox Controller

**To Reproduce**
1. Trying to type in a name for the file produces weird behavior. The cursor moves independently from the keyboard "highlight" and so you have to finagle it to work right.
2. Pressing up on the left joystick causes Zelda to enter "look around" mode. This happens after I unbound that in the controller menu. It usually lets you move forward for a bit until this starts.

**Comment by Mr-Wiseguy** [comment] 2024-06-18 22:35
I'm not quite sure what you mean by the first issue, can you send a video recording of it?

I also can't reproduce the second issue even with an xbox controller (and many people have used xbox controllers to play this without running into any issues like that), can you upload screenshots of your controller bindings?

**Comment by Mr-Wiseguy** [comment] 2024-06-25 01:51
Closing as nobody has been able to reproduce this issue, but feel free to respond if you can upload the two things I mentioned in my previous message (assuming you're still having the issue).

**Closed as not planned by Mr-Wiseguy** 2024-06-25 01:51 UTC
