### ISSUE TITLE
[Feature Request] navigate menus with dpad

### ISSUE THREAD

**Issue by powerpuffboysz** [Mr-Wiseguy/Zelda64Recomp#95] opened 2024-05-12 10:56 UTC
Would it be possible to make make the file select, name input, item menu etc navigable with the dpad of a controller?

**Comment by MultiKoopa** [comment] 2024-05-26 21:36
this would be great

**Comment by Mr-Wiseguy** [comment] 2024-06-11 22:45
Duplicate of #91.

**Closed as completed by Mr-Wiseguy** 2024-06-11 22:44 UTC
