### ISSUE TITLE
Game stutters during certain animations ONLY when streaming via moonlight/sunshine

### ISSUE THREAD

**Issue by Josef-Thorne-A** [Mr-Wiseguy/Zelda64Recomp#477] opened 2024-09-03 15:18 UTC
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**

555.58

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

**Describe the bug **
Game freezes for 1-3 seconds during certain animations. It seems to be when certain animations are taking place -- taking damage, hitting swords against walls, rolling into a wall, or especially charging your spin attack.

Changing settings, fps, etc. in Zelda64 appears to have no effect on the issue. 

**To Reproduce**
1. Stream game over Sunshine/Moonlight
2. Hit a wall with your sword, take damage from an enemy, or roll into a wall. Issue also briefly occurs on loading a save. Especially egregious when charging spin attack.
3. Stop streaming over sunshine
4. Issues will disappear

**Expected behavior**
All animations should be smooth

**Screenshots**
N/A

**Desktop (please complete the following information):**
  OS: Pop 22.04 jammy
 Kernel: x86_64 Linux 6.9.3-76060903-generic
 Resolution: 1440p
 DE: GNOME 41.4
 WM: Smithay X WM
 CPU: AMD Ryzen 9 7900 12-Core @ 24x 5.482GHz
 GPU: NVIDIA GeForce RTX 4070 Ti SUPER
 RAM: 9314MiB / 31701MiB

**Additional context**
I have also put in a support request with the Sunshine community.

**Comment by Mr-Wiseguy** [comment] 2024-09-03 15:21
Thanks for the report. If you set rumble to 0, does this still happen? If not, then this is a duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/233, which is caused by some issue with SDL's rumble functionality that I need to find a workaround for.

**Comment by Josef-Thorne-A** [comment] 2024-09-03 15:58
That did the trick! Sunshine was a red herring -- it was the controller that Sunshine connected.

**Comment by Mr-Wiseguy** [comment] 2024-09-03 15:59
Thanks for checking, closing this as a duplicate.

**Closed as completed by Mr-Wiseguy** 2024-09-03 15:59 UTC
