### ISSUE TITLE
[FEATURE REQUEST] Custom ui for different types of controllers.

### ISSUE THREAD

**Issue by DaRealCoolGamer2773** [Mr-Wiseguy/Zelda64Recomp#443] opened 2024-07-26 18:45 UTC
It's all in the title

**Comment by Mr-Wiseguy** [comment] 2024-07-26 18:51
Duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/292.

**Closed as completed by Mr-Wiseguy** 2024-07-26 18:51 UTC
