### ISSUE TITLE
[Feature Request / Question] Mouse support (analog camera)

### ISSUE THREAD

**Issue by BetaHD** [Mr-Wiseguy/Zelda64Recomp#426] opened 2024-07-02 19:05 UTC
I looked the analog camera feature up on youtube and the game gives a completely different feeling, when your able to use the right stick of the controller. 

But now heres my question: are you able to use "ONLY" the right stick or can you also use a mouse? 

I am a keyboard and mouse player and I only have a xbox 360 controller. I didnt found a way to use the mouse, even in the description of the Analog Camera setting ingame only the right stick is mentioned, but not the mouse. 

If the feature of using 360 camera on the mouse doesnt exist, can you make it a feature? And if yes, is it possible to bind keybinds to the mouse, so I also can attack with the mouse?

**Comment by Mr-Wiseguy** [comment] 2024-07-02 19:11
Currently it's only the right analog stick, but mouse freecam support is planned as well as stated in https://github.com/Zelda64Recomp/Zelda64Recomp/issues/183. Closing this as a duplicate of that issue.

**Closed as completed by Mr-Wiseguy** 2024-07-02 19:11 UTC
