### ISSUE TITLE
[BUG] Cutscenes are Grainy in 1.1.1 Release

### ISSUE THREAD

**Issue by loinmin** [Mr-Wiseguy/Zelda64Recomp#347] opened 2024-06-02 22:33 UTC
**Describe the bug**
Before 1.1.1 Cutscenes were not Grainy, now they are.

**To Reproduce**
1. Launch Game
2. Watch Intro/Any Cutscene

**Expected behavior**
Should not be Grainy, wasn't before 1.1.1

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/74041656/a9cb82d4-2774-4c95-b7c3-efbc46577715)

**Comment by Reonu** [comment] 2024-06-02 23:15
This is not a bug, it's intended behavior. Duplicate of #307 , you can see my full response there.

**Closed as completed** 2024-06-02 23:15 UTC
