### ISSUE TITLE
Button Mapping Overlaps

### ISSUE THREAD

**Issue by McBeefy34** [Mr-Wiseguy/Zelda64Recomp#167] opened 2024-05-17 01:10 UTC
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
Updated my computer and noticed the button mapping overlapped. 

**To Reproduce**
1. Update Windows
2. Open App
3. When game is open press the joystick in any direction.

**Expected behavior**
if i pressed down on the joystick, it would activate the c down button.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.0.0
 - CPU: Ryzen 7 5700x
 - GPU: NVIDIA GeForce RTX 3060 8GB

**Additional context**

**Comment by matthewmedway** [comment] 2024-05-17 17:07
I had this same problem and running `Zelda64Recompiled.exe` as administrator fixed it.

**Comment by Reonu** [comment] 2024-05-19 22:37
This is probably caused by Steam. Try closing Steam.

By default, if you have Steam controller support enabled, it will create a "desktop mapping" and emulate a keyboard, so Recomp might get duplicated inputs. If closing Steam solves the issue, then your options are:

- Close Steam when you want to play Zelda 64 Recompiled.
- Disable controller support on Steam.
- Add Zelda 64 Recompiled to Steam as a non-Steam app, and launch it from Steam.
- Apply a non-desktop controller template to your desktop controller bindings.

If you confirm that the problem is caused by Steam, please close the issue.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 03:51
Closing due to lack of response, feel free to reopen if the issue persists after trying Reonu's suggestion.

**Closed as completed by Mr-Wiseguy** 2024-06-11 03:51 UTC
