### ISSUE TITLE
Failed to clone 'lib/N64ModernRuntime' a second time, aborting

### ISSUE THREAD

**Issue by shoober420** [Mr-Wiseguy/Zelda64Recomp#388] opened 2024-06-10 09:30 UTC
Im trying to clone the repo, and encounter an error. This occurs when using Windows Git or MSYS2 Git.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:N64Recomp/N64ModernRuntime.git' into submodule path '/home/RavenWolf_-/Zelda64Recomp/lib/N64ModernRuntime' failed
Failed to clone 'lib/N64ModernRuntime' a second time, aborting

**To Reproduce**
1. git clone --recurse-submodules https://github.com/Zelda64Recomp/Zelda64Recomp.git

**Expected behavior**
Clone completion

**Desktop:**
 - OS: Windows 11
 - Version: git master (https://github.com/Zelda64Recomp/Zelda64Recomp/commit/0e31d3b582e82484688107ea543f8c27805a88d3)
 - CPU: Ryzen 4900
 - GPU: Geforce 2060
 - GPU driver: NVIDIA 555.99

**Comment by dcvz** [comment] 2024-06-10 10:33
Is there anything more in the console about the error?

**Comment by shoober420** [comment] 2024-06-10 11:35
Full Log:

git clone --recurse-submodules https://github.com/Zelda64Recomp/Zelda64Recomp.git

Cloning into 'Zelda64Recomp'...
remote: Enumerating objects: 3827, done.
remote: Counting objects: 100% (1440/1440), done.
remote: Compressing objects: 100% (320/320), done.
remote: Total 3827 (delta 1266), reused 1153 (delta 1120), pack-reused 2387
Receiving objects: 100% (3827/3827), 8.15 MiB | 19.73 MiB/s, done.
Resolving deltas: 100% (2688/2688), done.
Submodule 'lib/N64ModernRuntime' (git@github.com:N64Recomp/N64ModernRuntime.git) registered for path 'lib/N64ModernRuntime'
Submodule 'lib/RmlUi' (https://github.com/mikke89/RmlUi/) registered for path 'lib/RmlUi'
Submodule 'lib/freetype-windows-binaries' (https://github.com/ubawurinna/freetype-windows-binaries) registered for path 'lib/freetype-windows-binaries'
Submodule 'lib/lunasvg' (https://github.com/sammycage/lunasvg) registered for path 'lib/lunasvg'
Submodule 'lib/mm-decomp' (https://github.com/zeldaret/mm) registered for path 'lib/mm-decomp'
Submodule 'lib/rt64' (https://github.com/rt64/rt64) registered for path 'lib/rt64'
Submodule 'lib/sse2neon' (https://github.com/DLTcollab/sse2neon.git) registered for path 'lib/sse2neon'
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/N64ModernRuntime'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:N64Recomp/N64ModernRuntime.git' into submodule path 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/N64ModernRuntime' failed
Failed to clone 'lib/N64ModernRuntime'. Retry scheduled
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/RmlUi'...
remote: Enumerating objects: 34900, done.
remote: Counting objects: 100% (6875/6875), done.
remote: Compressing objects: 100% (1407/1407), done.
remote: Total 34900 (delta 5977), reused 5793 (delta 5426), pack-reused 28025
Receiving objects: 100% (34900/34900), 30.78 MiB | 27.13 MiB/s, done.
Resolving deltas: 100% (25857/25857), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/freetype-windows-binaries'...
remote: Enumerating objects: 1089, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1089 (delta 0), reused 0 (delta 0), pack-reused 1087
Receiving objects: 100% (1089/1089), 23.33 MiB | 31.93 MiB/s, done.
Resolving deltas: 100% (773/773), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/lunasvg'...
remote: Enumerating objects: 2601, done.
remote: Counting objects: 100% (711/711), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 2601 (delta 610), reused 602 (delta 594), pack-reused 1890
Receiving objects: 100% (2601/2601), 1.59 MiB | 7.01 MiB/s, done.
Resolving deltas: 100% (1701/1701), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/mm-decomp'...
remote: Enumerating objects: 72406, done.
remote: Counting objects: 100% (951/951), done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 72406 (delta 328), reused 621 (delta 209), pack-reused 71455
Receiving objects: 100% (72406/72406), 117.54 MiB | 25.60 MiB/s, done.
Resolving deltas: 100% (43182/43182), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/rt64'...
remote: Enumerating objects: 1182, done.
remote: Counting objects: 100% (567/567), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 1182 (delta 339), reused 436 (delta 269), pack-reused 615
Receiving objects: 100% (1182/1182), 1.04 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (591/591), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/sse2neon'...
remote: Enumerating objects: 4847, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 4847 (delta 126), reused 184 (delta 106), pack-reused 4624
Receiving objects: 100% (4847/4847), 2.61 MiB | 9.45 MiB/s, done.
Resolving deltas: 100% (3289/3289), done.
Cloning into 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/N64ModernRuntime'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:N64Recomp/N64ModernRuntime.git' into submodule path 'C:/Users/Raven/Downloads/Zelda64Recomp/lib/N64ModernRuntime' failed
Failed to clone 'lib/N64ModernRuntime' a second time, aborting

**Comment by dcvz** [comment] 2024-06-10 11:36
Your issue seems to be `Host key verification failed.` probably at some point it asked you if you wanted to trust the github url and you might've said no?

**Comment by shoober420** [comment] 2024-06-10 11:40
How can I tell git to trust the URL?

**Comment by shoober420** [comment] 2024-06-10 12:42
Using MSYS2, I deleted the "/etc/ssh" directory and the "~/.ssh" directory. Upon doing this and running "git clone --recurse-submodules https://github.com/Zelda64Recomp/Zelda64Recomp.git", I still get the same error, even though it asked me to continue connecting after accepting the key and answering "yes". Here is the full log.

git clone --recurse-submodules https://github.com/Zelda64Recomp/Zelda64Recomp.git
Cloning into 'Zelda64Recomp'...
remote: Enumerating objects: 3827, done.
remote: Counting objects: 100% (1437/1437), done.
remote: Compressing objects: 100% (318/318), done.
remote: Total 3827 (delta 1263), reused 1152 (delta 1119), pack-reused 2390
Receiving objects: 100% (3827/3827), 8.15 MiB | 19.92 MiB/s, done.
Resolving deltas: 100% (2686/2686), done.
Submodule 'lib/N64ModernRuntime' (git@github.com:N64Recomp/N64ModernRuntime.git) registered for path 'lib/N64ModernRuntime'
Submodule 'lib/RmlUi' (https://github.com/mikke89/RmlUi/) registered for path 'lib/RmlUi'
Submodule 'lib/freetype-windows-binaries' (https://github.com/ubawurinna/freetype-windows-binaries) registered for path 'lib/freetype-windows-binaries'
Submodule 'lib/lunasvg' (https://github.com/sammycage/lunasvg) registered for path 'lib/lunasvg'
Submodule 'lib/mm-decomp' (https://github.com/zeldaret/mm) registered for path 'lib/mm-decomp'
Submodule 'lib/rt64' (https://github.com/rt64/rt64) registered for path 'lib/rt64'
Submodule 'lib/sse2neon' (https://github.com/DLTcollab/sse2neon.git) registered for path 'lib/sse2neon'
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/N64ModernRuntime'...
The authenticity of host 'github.com (FOO)' can't be established.
ED25519 key fingerprint is SHA256:FOO.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:N64Recomp/N64ModernRuntime.git' into submodule path '/home/RavenWolf_-/Zelda64Recomp/lib/N64ModernRuntime' failed
Failed to clone 'lib/N64ModernRuntime'. Retry scheduled
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/RmlUi'...
remote: Enumerating objects: 34900, done.
remote: Counting objects: 100% (6880/6880), done.
remote: Compressing objects: 100% (1411/1411), done.
remote: Total 34900 (delta 5987), reused 5792 (delta 5427), pack-reused 28020
Receiving objects: 100% (34900/34900), 30.78 MiB | 22.53 MiB/s, done.
Resolving deltas: 100% (25862/25862), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/freetype-windows-binaries'...
remote: Enumerating objects: 1089, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1089 (delta 0), reused 0 (delta 0), pack-reused 1087
Receiving objects: 100% (1089/1089), 23.33 MiB | 33.59 MiB/s, done.
Resolving deltas: 100% (773/773), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/lunasvg'...
remote: Enumerating objects: 2601, done.
remote: Counting objects: 100% (860/860), done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 2601 (delta 700), reused 702 (delta 644), pack-reused 1741
Receiving objects: 100% (2601/2601), 1.58 MiB | 6.75 MiB/s, done.
Resolving deltas: 100% (1702/1702), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/mm-decomp'...
remote: Enumerating objects: 72406, done.
remote: Counting objects: 100% (951/951), done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 72406 (delta 328), reused 621 (delta 209), pack-reused 71455
Receiving objects: 100% (72406/72406), 118.85 MiB | 24.32 MiB/s, done.
Resolving deltas: 100% (43386/43386), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/rt64'...
remote: Enumerating objects: 1182, done.
remote: Counting objects: 100% (567/567), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 1182 (delta 339), reused 436 (delta 269), pack-reused 615
Receiving objects: 100% (1182/1182), 1.04 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (591/591), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/sse2neon'...
remote: Enumerating objects: 4847, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 4847 (delta 126), reused 184 (delta 106), pack-reused 4624
Receiving objects: 100% (4847/4847), 2.61 MiB | 5.16 MiB/s, done.
Resolving deltas: 100% (3289/3289), done.
Cloning into '/home/RavenWolf_-/Zelda64Recomp/lib/N64ModernRuntime'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:N64Recomp/N64ModernRuntime.git' into submodule path '/home/RavenWolf_-/Zelda64Recomp/lib/N64ModernRuntime' failed
Failed to clone 'lib/N64ModernRuntime' a second time, aborting

**Comment by SilverCard** [comment] 2024-06-10 14:32
Same problem here.

In the file .gitmodules, i changed "`url = git@github.com:N64Recomp/N64ModernRuntime.git`" to "`url = https://github.com/N64Recomp/N64ModernRuntime.git`" and this fixed the problem.

The submodule N64ModernRuntime is the only one with SSH instead HTTPS.

**Comment by briaguya0** [comment] 2024-06-10 14:32
i believe the problem is that the submodule is using `git@` instead of `https:`

https://github.com/Zelda64Recomp/Zelda64Recomp/blob/0e31d3b582e82484688107ea543f8c27805a88d3/.gitmodules#L21

i'm surprised i haven't encountered this issue, as i've definitely run into ssh issues with `git@` defined submodules for repos i don't have write access to before

i believe updating that submodule to use https (like the rest of the submodules listed in `.gitmodules`) is a good solution here

**Comment by dcvz** [comment] 2024-06-10 14:34
We should actually change this. This is leftover from when that repo was in development and not public. 

It might only work for users to have an ssh key set on their computers.

**Comment by Mr-Wiseguy** [comment] 2024-06-10 14:34
Oh yeah, that should have been https and not ssh, good catch.

**Comment by dcvz** [comment] 2024-06-10 14:51
This is now be fixed by #389 - thanks for reporting!

**Closed as completed by dcvz** 2024-06-10 14:51 UTC
