### ISSUE TITLE
[Feature Request] Free Camera Mouse Support

### ISSUE THREAD

**Issue by TSEG6** [Mr-Wiseguy/Zelda64Recomp#291] opened 2024-05-27 11:46 UTC
I'm surprised this wasn't added with the free camera option.
But moving the camera around using the mouse would be a very nice addition if you use mouse and keyboard to play.
Especially since you can use the mouse already when aiming.

**Comment by JamesK48** [comment] 2024-05-27 19:55
How do you use the mouse when aiming, I can't get that to work? Thanks

**Comment by TSEG6** [comment] 2024-05-27 20:24
In the settings menu make sure your mouse sensitivity is higher than 0, which it's defaulted to. It also only works when using certain items like the bow, hookshot & deku bubbles

**Comment by Reonu** [comment] 2024-05-27 20:32
This is a planned feature, including mouse button bindings!

**Comment by Reonu** [comment] 2024-05-27 20:32
Closing as duplicate of #183 though

**Closed as completed by Reonu** 2024-05-27 20:32 UTC
