### ISSUE TITLE
[Feature Request] Separate controls only when playing ocarina

### ISSUE THREAD

**Issue by cptnoblivious** [Mr-Wiseguy/Zelda64Recomp#472] opened 2024-08-26 19:30 UTC
Please consider an ability to have a specific set of controls while playing the ocarina. Here's my use-case:

Controls (Xinput)
```
Ocarina D: Dpad Down
Ocarina F: A
Ocarina A: B
Ocarina B: X
Ocarina D(8va): Y
Return from ocarina: Dpad Up
```

This matches the mapping of the N64 controller to my liking. However, using the second button mapping slot does not work here. Whatever I've mapped to B (N64) cancels playing, and my mapped A (Xinput) to A (N64) just plays the D note.

It's a big ask, and surely requires watching the game state, but having a separate section for mapping controls while playing an instrument would improve my play experience quite a bit. I could never get behind using the right stick for this.

**Comment by Mr-Wiseguy** [comment] 2024-08-28 03:43
Duplicate of #422, dedicated ocarina mappings are something I'd like to add at some point.

**Closed as completed** 2024-08-28 03:44 UTC
