### ISSUE TITLE
bank

### ISSUE THREAD

**Issue by Mrgoodwrench481** [Mr-Wiseguy/Zelda64Recomp#398] opened 2024-06-15 19:50 UTC
will not allow me to take out over 100 rupees from bank when having adults wallet

## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

**Describe the bug**

**To Reproduce**
2. etc.

**Expected behavior**

**Screenshots**
Please attach a screenshot of the bug.

**Desktop (please complete the following information):**
 - OS: [Windows 10, Windows 11, Linux distro]
 - Version: [e.g. 1.0.0]
 - CPU: [e.g. Intel Core ..., AMD Ryzen ..., etc.]
 - GPU: [e.g. NVIDIA GeForce .../Radeon RX .../Intel UHD .../etc.]
 - GPU driver: [e.g Nvidia driver 545.XX, AMD driver 24.X.X, etc]

**Additional context**

**Comment by Mr-Wiseguy** [comment] 2024-06-15 19:51
Can you send your save file? There's not much we can check on our side without it, since this is working fine for everybody else.

**Comment by Mrgoodwrench481** [comment] 2024-06-16 01:33
I’ll try to figure it out and send it to you

**Comment by Mr-Wiseguy** [comment] 2024-06-18 22:36
Closing this for now since we can't reproduce the issue. If you can record a video of the issue or send your save file then feel free to reopen.

**Closed as completed by Mr-Wiseguy** 2024-06-18 22:36 UTC

**Comment by Mrgoodwrench481** [comment] 2024-06-19 12:52
It was actually my fault, sorry for the inconvenience.
