### ISSUE TITLE
[Feature Request] Japanese support

### ISSUE THREAD

**Issue by tanabesan222** [Mr-Wiseguy/Zelda64Recomp#202] opened 2024-05-19 19:15 UTC
Hello.
I'm japanese so I mostly play my games in japanese. My english isnt good enough to understand it. I saw this project and i wanted to import a japanese rom but I can't. So I would be very happy if you could integrate japanese support. Maybe it would also be helpful for other people.
Thank you for reading

**Comment by JikoKinsoku** [comment] 2024-05-19 20:19
たぶんモッドサポートを待ちなさいです。
We'll probably have to wait for "Mod Support."

**Comment by Reonu** [comment] 2024-05-19 22:21
Thanks for the issue!

What you need to wait for is not "mod support", but "multilanguage support". Once multilanguage support is in, it will be possible to add Japanese support. Multilanguage support will be a part of the project itself, regardless of the ROM beign used, and it should be possible to add any language.

Closing as duplicate of #97

**Closed as completed by Reonu** 2024-05-19 22:21 UTC
