### ISSUE TITLE
Unable to map Right C on Switch N64 controller

### ISSUE THREAD

**Issue by DrakenStark** [Mr-Wiseguy/Zelda64Recomp#261] opened 2024-05-25 04:24 UTC
Right C on the Switch N64 controller by default acts as the select button on a regular controller. Due to this, Right C cannot be mapped to.

To work around this issue entirely, please allow the Recomp Menu to be remapped on controllers and add Select as a map-able button.

**Comment by Drihscol** [comment] 2024-05-25 04:37
Known issue, current workaround is to launch through steam and remap C right using steaminput

**Comment by Mr-Wiseguy** [comment] 2024-05-25 05:12
Duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/41

**Closed as completed by Mr-Wiseguy** 2024-05-25 05:12 UTC
