### ISSUE TITLE
(Suggestion) Save editor 

### ISSUE THREAD

**Issue by 111ebobo** [Mr-Wiseguy/Zelda64Recomp#414] opened 2024-06-23 21:12 UTC
Can you make a save editor for this games, so we can change some things to our data or change the game progress if we lose it, I understand that it can be out of scope but it can be useful for some ways

**Comment by Mr-Wiseguy** [comment] 2024-06-25 01:39
Duplicate of #268.

**Closed as completed by Mr-Wiseguy** 2024-06-25 01:39 UTC
