### ISSUE TITLE
[Feature Request] Add native support for N64 controllers

### ISSUE THREAD

**Issue by Cameron9635** [Mr-Wiseguy/Zelda64Recomp#109] opened 2024-05-12 21:27 UTC
Tried hooking up my N64 controller with a USB adapter and it wouldn't work. This same setup works with other N64 emulators.

**Comment by rkroll17** [comment] 2024-05-12 22:18
I have the same issue. C-Right is being detected as the escape button and I cannot assign it to C-Right in game.

**Comment by rkroll17** [comment] 2024-05-12 22:23
Also duplicate of issue #41

**Comment by Mr-Wiseguy** [comment] 2024-06-11 03:37
Closing as duplicate of #41 and because rebinding the menu button was added in 1.1.0.

**Closed as completed by Mr-Wiseguy** 2024-06-11 03:37 UTC
