### ISSUE TITLE
Sound is not working properly

### ISSUE THREAD

**Issue by niklakis** [Mr-Wiseguy/Zelda64Recomp#22] opened 2024-05-10 22:46 UTC
The game sounds like this

https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/5071672/d0653f0f-cb1c-49a8-97e2-7cc82794c464

**Comment by Mr-Wiseguy** [comment] 2024-05-10 22:56
Thanks for the bug report! What operating system (Win 10/11/Linux) are you on, and what CPU/GPU do you have? That might help me track down the cause of the issue.

**Comment by niklakis** [comment] 2024-05-10 23:00
Sorry I didn't include this info in the first place, it slipped my mind. Win 11, R5 5600, RX 6700XT. If you need any more info feel free to ask.

**Comment by niklakis** [comment] 2024-05-10 23:03
Also, here are my graphics settings. I initially suspected the framerate but even original has the same result.

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/5071672/d1dd5d51-bd2a-4037-9094-e7e351561846)

**Comment by Mr-Wiseguy** [comment] 2024-05-10 23:10
Do you have any sort of special sound setup? Your specs should be plenty to run this at full speed without an audio issue, so I don't think it's caused by performance at least.

**Comment by niklakis** [comment] 2024-05-10 23:15
Just the good old realtek sound found on my mobo. MSI B550 Tomahawk on the latest bios with the latest realtek drivers.

**Comment by Mr-Wiseguy** [comment] 2024-05-10 23:35
Good to know. It seems like recomp thinks there's too much audio latency and is trying to compensate by speeding up the audio to catch up when it shouldn't be. I'll see if I can spot a reason why this might be happening and may send a custom build if I can come up with a potential fix.

**Comment by niklakis** [comment] 2024-05-10 23:44
Not the first time I have had weird audio issues with ryzen. Both a 3600 and my 5600 system have a weird issue with cemu and botw where the audio in shrines sounds kinda harsh. Nowhere near as much of an issue as this but still an issue. I was told it's caused by infinity fabric shenanigans that are beyond my understanding lol.

**Comment by Squall-Leonhart** [comment] 2024-05-11 00:41
This is a bit if an issue in SDL's mixer, it should be fixed in 3.x eventually since they've scrapped 2.x's and implemented it from scratch, some of the behavior of 3.x's is ported back to 2.30's latest release but there might still be some edge cases that mess up.

Basically if you have the system set to X sample rate and SDL set to Y sample rate, the sdl mixer can speed up or slow down depending on which direction you're going with the resampling if you've opted out of using WASAPI mixing for some reason, this was made the default again in 2.26, but if you've opted to using sdl's internal mixer that would be a place to check.

**Comment by JimBimBum** [comment] 2024-05-11 03:39
i can confirm i'm also having this issue on linux as well. endevourOS distro

**Comment by VikingSchism** [comment] 2024-05-11 15:13
Having a similar issue on Manjaro - it seems to affect sound for the entire system for me causing audio to crackle - though it doesn't sound quite as distorted
I'm using an Nvidia 4070 Super, and a Ryzen 7 5800X

**Comment by Squall-Leonhart** [comment] 2024-05-11 21:07
are these motherboards using the USB version of Realtek Audio?

**Comment by niklakis** [comment] 2024-05-11 21:16
Is there an easy way to see what my mobo uses?

**Comment by Squall-Leonhart** [comment] 2024-05-11 21:40
the motherboard specs page usually differentiates between Realtek audio and Realtek usb audio.

**Comment by niklakis** [comment] 2024-05-11 21:42
It doesn't say usb so pcie i guess ¯\_(ツ)_/¯

**Comment by Salaxio** [comment] 2024-05-12 16:55
Exact same issue on my laptop running Win 11, i5-11400H, Nvidia 3050Ti and I do use a USB headset, tho the issue is also present with the laptop speakers.

**Comment by VikingSchism** [comment] 2024-05-12 20:47
> i can confirm i'm also having this issue on linux as well. endevourOS distro

I've managed to figure out on my end that setting tsched to 0 in pulseaudio fixes the issue for me. Not sure why only this application seems to cause the issue for me, but this has eliminated the crackling/garbled sound. May be worth trying for your situation @JimBimBum

**Comment by linkyammp** [comment] 2024-05-14 11:15
I have the same issue. Win 10, i5-12400F, RTX 3070, MSI PRO B660M-P DDR4. Realtek audio drivers are installed

**Comment by MissBoobarella** [comment] 2024-05-20 13:57
Same issue here. Laptop - i7-13700HX, 32GB, 4070, Windows 11 Pro 22H2.
I have a Audio interface, Behringer UMD404HD with changeable sample rate and buffer size, but whichever option i choose it always does the crackling. Issue happens in external speakers/laptop speakers/bluetooth.
There is only another application that does the same - SCRCPY.exe, an android screen mirroring tool. In there i need to use a command to increase the audio buffer size (--audio-output-buffer=10) in order to stop the crackling. 
All other applications/games work correctly. 
Thanks for your work!

Edit:
So, i was messing around with Chat GPT to try and find a solution and it mentioned Environment Variables and changing "SDL_AUDIODRIVER" from "directsound" to other things. And after trying a bit I discovered that setting that variable as "wasapi" solved the issue for me! I've yet to try if everything that was working before continues to work correctly but overall it seems to be working. If someone knows why I shouldn't change this or knows if it is a bad idea i'm all ears, i just found something that helped my case and want to help others.

Steps: 
search windows 11 for environment and choose "Edit the system environment variables"
On the bottom of the new window click the button "Environment Variables..."
On the new window, on the System Variables part of the window look for "SDL_AUDIODRIVER" variable, select it and click Edit
*Remember the default value before changing it so you can rollback if needed - mine was "directsound"!*
Change the Variable value to "wasapi" without the quotes, click Ok and then Ok again to close the Environment Variables Window.
Try to run the Zelda64 executable and check if it now sounds correctly. If not you can go back to the variable and change it to other options like "winmm".

Hope this helps!

**Comment by theofficialgman** [comment] 2024-05-21 22:24
I experience this on one of my ARM64 Linux system (ubuntu jammy) that uses pulseaudio by default

overwriting SDL2 to use alsa seems to workaround the issue `SDL_AUDIODRIVER=alsa`

on my other ARM64 system (ubuntu noble) that uses pipewire by default (with pipewire-pulse and pipewire-alsa installed) I don't have problems

In both cases, SDL defaults to pulseaudio output.

**Comment by Salaxio** [comment] 2024-05-22 01:21
The workaround provided by @MissBoobarella worked for me and it also solved issues with other programs using SDL2 (Simple64 for example). Thanks a lot !

**Comment by niklakis** [comment] 2024-05-24 15:26
I closed the issue but as @MissBoobarella said I don't know for sure if there are any downsides to doing this. So far I haven't noticed anything wrong.

**Comment by Mr-Wiseguy** [comment] 2024-05-26 08:15
Reopening for visibility until this is properly solved.

**Comment by Mr-Wiseguy** [comment] 2024-05-27 03:42
For everyone in this thread on Windows, does 1.1.0 fix the issue without needing the workaround? I added some code to force a specific SDL audio backend on Windows.

**Comment by niklakis** [comment] 2024-05-27 08:21
It works! I changed SDL_AUDIODRIVER back to directsound, tested the previous version to verify it still has the issue (it does) and then tested the new one and it's fixed. Thank you!

**Comment by Salaxio** [comment] 2024-05-27 12:33
can also confirm 1.1.0 fixes the issue !

**Comment by Reonu** [comment] 2024-05-27 12:39
Fixed in 1.1.0

**Closed as completed by Reonu** 2024-05-27 12:39 UTC
