### ISSUE TITLE
Noisy motion blur

### ISSUE THREAD

**Issue by minarru** [Mr-Wiseguy/Zelda64Recomp#307] opened 2024-05-28 17:01 UTC
**Describe the bug**
Any cinematic with motion blur displays with RGB? noise, this didn't happen on versions 1.0.0/1.0.1.
This happens whether RTX HDR is enabled or disabled, using in-game frame limiter.

1. Start the game
2. Let the intro cutscene play
Or
1. Play the Song of Time (or  Song of Soaring)

Screenshot:
![Zelda64recompiled-v1 1 0-windows_ 2024 05 28 - 18 33 14 09 - frame at 0m5s](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/35364118/f5a82507-d0d0-4ba8-8987-c5b3ebd6ff3d)

Downscaled video:
https://github.com/Zelda64Recomp/Zelda64Recomp/assets/35364118/97bfaeed-eabd-4335-a57e-aa8767b44b4f

 - OS: Windows 11
 - Version: 1.1.0
 - CPU: AMD Ryzen 7800X3D
 - GPU: NVIDIA GeForce RTX 4080
 - GPU driver: Nvidia driver 555.85

**Comment by minarru** [comment] 2024-05-28 17:05
Screenshot from 1.0.1:
![Zelda64recompiled-v1 0 1-windows Screenshot 2024 05 28 - 19 03 10 45](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/35364118/2463fc63-8bfe-441c-a6d9-9a3071ae727b)

This is with RTX HDR on, that's why the saturation looks intense

**Comment by Reonu** [comment] 2024-05-28 17:11
This is intended behavior. The game does this on original hardware, it's an intentional artistic decision by the original developers. It being missing on 1.0.0 was a bug of the project which is now fixed. 

There is a shortcoming in where the noise should not be noticeable where the screen is black in order to 100% match console, as explained [here](https://github.com/Zelda64Recomp/Zelda64Recomp/issues/305#issuecomment-2135238046) by Darío. But the noise effect itself is very much intentional.

Closing as duplicate & intended behavior.

**Closed as completed by Reonu** 2024-05-28 17:11 UTC
