### ISSUE TITLE
Expected performance

### ISSUE THREAD

**Issue by KainXVIII** [Mr-Wiseguy/Zelda64Recomp#68] opened 2024-05-11 18:31 UTC
Is it normal that my pc can't hold 60 fps (interpolated) at 1080p (no AA) most of the time? I know, i know - my pc is old 😅
PS - also it will be nice to include internal FPS counter (and other stats), because you don't recommend enabling MSI afterburner..

 - OS: Windows 10
 - Version: latest
 - CPU: i5-3570
 - GPU: GTX 970

![Снимок экрана (3837)](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16922126/2f12e387-3841-4280-a9b1-0dc60b9b9ddc)

**Comment by OG0mez** [comment] 2024-05-11 18:39
Could it be, currently testing on 

- OS: Windows 10
- Version: latest
- CPU: Ryzen 5 5600
- GPU: RTX 4060

1440p@144hz   no issues

**Comment by KainXVIII** [comment] 2024-05-11 18:44
> Could it be, currently testing on
> 
> * OS: Windows 10
> * Version: latest
> * CPU: Ryzen 5 5600
> * GPU: RTX 4060
> 
> 1440p@144hz no issues

Thanks, also should be interesting to see results from comparable to my pc setup..

**Comment by FailerO** [comment] 2024-05-11 19:56
Looks like a RAM bottleneck.

**Comment by JimBimBum** [comment] 2024-05-12 03:50
whoa 5GBs of ram? that seems more like a ram leak.

**Comment by KainXVIII** [comment] 2024-05-12 09:03
Original resolution (even with downsampling) is much smoother, GPU/CPU usage is almost the same though (if you can trust what MSI Afterburner shows)
![Снимок экрана (3839)](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16922126/47d54d45-76d7-4a9d-8d28-fef2f2412bae)

**Comment by Deozaan** [comment] 2024-05-16 07:41
My system is older than yours and the game seems to run great for me.

### PC Specs
- OS: Windows 10 22H2
- CPU: i7 2600K
- GPU: GTX 670
- RAM: 16GB
- Resolution: 2560x1440@60hz
### Game Graphics Configuration
- Resolution: Auto
- Downsampling: N/A
- Aspect Ratio: Expand
- Window Mode: Fullscreen
- Framerate: Display
- MSAA: N/A
- HUD Placement: 16:9

That said, I don't have an FPS counter on-screen so maybe it's running at 50-60 FPS and I just don't notice. It feels very smooth to me.

**Comment by Reonu** [comment] 2024-05-16 07:47
Well, does it hold 60 FPS if you don't use MSI Afterburner?

You can add Recomp to Steam and use Steam's FPS counter. That doesn't seem to cause any performance issues.

Also, your GPU seems to be running at very low clocks. Try going to the Nvidia Control Panel, go to manage 3D settings, add the Recomp exe, and set "power management" to "Prefer maximum performance". Might be unrelated but it's worth a try.

Also make sure your drivers are up to date.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 03:28
Closing since there hasn't been a response in a month and because this seems to be an outlier, if you've tried Reonu's suggestion and it didn't fix the issue then feel free to reopen.

**Closed as completed by Mr-Wiseguy** 2024-06-11 03:28 UTC

**Comment by KainXVIII** [comment] 2024-06-11 10:05
> Well, does it hold 60 FPS if you don't use MSI Afterburner?
> 
> You can add Recomp to Steam and use Steam's FPS counter. That doesn't seem to cause any performance issues.
> 
> Also, your GPU seems to be running at very low clocks. Try going to the Nvidia Control Panel, go to manage 3D settings, add the Recomp exe, and set "power management" to "Prefer maximum performance". Might be unrelated but it's worth a try.
> 
> Also make sure your drivers are up to date.

"Prefer maximum performance" helps a little, but there are still slowdowns during intro with mask and motion blur (50 fps) and when you load a save file from owl statue (down to 30 fps) but then its improves to 60, so i don't know, its not ideal.

**Comment by Reonu** [comment] 2024-06-11 10:27
That's shader compilation causing performance issues since your CPU is a bit weak.

Try going to `%LOCALAPPDATA%\Zelda64Recompiled` and in graphics.json change the graphics api to `Vulkan`. In our testing, DX12 performs better than Vulkan once shaders are compiled, but shader compilation is faster on Vulkan. It might be worth it on your system.

**Comment by KainXVIII** [comment] 2024-06-11 10:30
> That's shader compilation causing performance issues since your CPU is a bit weak.
> 
> Try going to `%LOCALAPPDATA%\Zelda64Recompiled` and in graphics.json change the graphics api to `Vulkan`. In our testing, DX12 performs better than Vulkan once shaders are compiled, but shader compilation is faster on Vulkan. It might be worth it on your system.

Hmm, if its shader compilation stutter then why its happens every time i boot the game?
Thanks, i will try Vulkan next!

**Comment by KainXVIII** [comment] 2024-06-11 21:35
Vulkan is faster for me indeed, there are still slowdowns after you load a save file, but rotating mask intro is almost flawless now.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 21:42
This will be resolved for D3D12 when DXIL patching is added to RT64. The root cause is just that the D3D12 backend for RT64 currently compiles shaders from source from runtime, which takes noticeably longer on a CPU like yours with only 4 threads. RT64 also doesn't store compiled shaders on the hard drive between play sessions in order to avoid using unnecessary disk space, which is why it happens on each session. In the meantime we'll be leaving D3D12 as the default backend for the reasons outlined [here](https://github.com/N64Recomp/N64Recomp/issues/63#issuecomment-2123145357) (you can skip to the bullet point list for a summary), since it's still a much better experience in Windows on the average user's CPU.

**Comment by KainXVIII** [comment] 2024-06-12 10:53
> This will be resolved for D3D12 when DXIL patching is added to RT64. The root cause is just that the D3D12 backend for RT64 currently compiles shaders from source from runtime, which takes noticeably longer on a CPU like yours with only 4 threads. RT64 also doesn't store compiled shaders on the hard drive between play sessions in order to avoid using unnecessary disk space, which is why it happens on each session. In the meantime we'll be leaving D3D12 as the default backend for the reasons outlined [here](https://github.com/N64Recomp/N64Recomp/issues/63#issuecomment-2123145357) (you can skip to the bullet point list for a summary), since it's still a much better experience in Windows on the average user's CPU.

Thanks, i will wait for the version with shader cache store support (helps in Cemu emulator)! Meanwhile Vulkan is a good alternative for low-end pcs.
