### ISSUE TITLE
on relaunch Items unusable

### ISSUE THREAD

**Issue by Trollagerale** [Mr-Wiseguy/Zelda64Recomp#240] opened 2024-05-22 06:51 UTC
After exiting the game yesterday, loading into the game all items and weapons have become unusable

reload, death, and computer restart do not resolve issue.

**To Reproduce**
unknown

**Expected behavior**
items/ weapons usable

**Screenshots**
Bug visible in game
![bug](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/170501462/365a3698-2b8d-4b77-9c14-5179c19e421a)
 Controller scheme
![bug1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/170501462/65e8982e-4f21-4b8b-8677-06541cc9a9a9)

 - OS: windows 10 pro
 - Version: 22h2
 - CPU: intel i5-10600k
 - GPU: EVGA 3070-TI

**Comment by Reonu** [comment] 2024-05-22 09:38
Hello, could you post your savefile here so that we can look into it? 

The savefile is located in `%LOCALAPPDATA%\Zelda64Recompiled\saves`

Also, what were you doing in-game when you closed the game yesterday? Did you save manually or did you use the autosave feature?

Thanks.

**Comment by Trollagerale** [comment] 2024-05-22 11:12
Manually saved at the Southern Swamp owl statue (Auto save was enabled at the time). Upon reopen instead of being at the Southern swamp owl statue I was in front of the clock tower, Like dawn of first day but with all items i had collected up to that point.

since original bug post I started a new game in save slot 2 and have disabled auto save. Checking save 1 before upload it now appears to be in an odd state and have encountered a new repeatable bug.

new repeatable bug: If the game is closed with alt + F4 then select quit option the game is reverted to dawn of first day post first fight with majora. All progression during second 3 day cycle lost only first cycle retained. - (auto save: disabled)


[mm.n64.us.1.0.zip](https://github.com/Zelda64Recomp/Zelda64Recomp/files/15401794/mm.n64.us.1.0.zip)

**Comment by Mr-Wiseguy** [comment] 2024-06-11 04:54
The save file you attached isn't the one shown in the original picture and does not have the issue.

> new repeatable bug: If the game is closed with alt + F4 then select quit option the game is reverted to dawn of first day post first fight with majora. All progression during second 3 day cycle lost only first cycle retained. - (auto save: disabled)

That is the intended behavior, existing autosaves get treated as owl saves (and so are deleted on load) when you disable autosaving. It's stated in the description of the autosave feature in the menu.

Closing as there's not enough information here to reproduce the issue. Feel free to reopen it if you run into the issue again or if you still have the original save file shown in the first picture.

**Closed as completed by Mr-Wiseguy** 2024-06-11 04:54 UTC
