### ISSUE TITLE
Noise/grain on title screen on 1.1.0

### ISSUE THREAD

**Issue by parski** [Mr-Wiseguy/Zelda64Recomp#305] opened 2024-05-28 12:03 UTC
**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**
555.85

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
I have not checked.

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**
Intended mechanics.

**Describe the bug**
Seeing a lot of noise on the title screen. I also saw in on another screen which I do not recall but gameplay is fine.

**To Reproduce**
Press Start Game in Recomp GUI.

**Expected behavior**
No noise on title screen.

**Screenshots**

\[Edit\] _Had to resize the image to 1920x1080 because 3840x2160 was too large to upload on GitHub._

![Screenshot 2024-05-28 135513](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/2445818/0319b1f5-9e9b-4dfc-a891-067b4e6c7a6f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 build 22631.3593
 - CPU: AMD Ryzen 7800X3D
 - GPU: NVIDIA RTX 4090
 - GPU driver: 555.85

**Additional context**
Worked fine in 1.0.0, which I upgraded from by removing 1.0.0 and extracting 1.1.0. I start the game via Steam Big Picture.

**Comment by Wolgwang** [comment] 2024-05-28 13:33
I think this behavior is intentional and was present in the N64 version. You can even find it mentioned in the changelogs.

**Comment by DarioSamo** [comment] 2024-05-28 13:35
Hello, this is pretty much intentional for now as the noise effect from dithering is applied on the high precision.

Sadly, one thing that can't be accurately replicated (yet) is that due to rounding down to 16-bit precision in hardware, the noise effect will pretty much disappear when the screen is completely black. But on hardware you'll see the effect pop up as soon as the background turns up the intensity slightly. The only solution from our side would be to drop down the color precision to 16-bit for this problem to disappear.

A future solution might involve just doing the dithering effect by using a technique that samples the framebuffer directly and ignores the noise for cases where the screen is completely black.

**Comment by Reonu** [comment] 2024-05-28 13:45
Closing as intended behavior

**Closed as completed by Reonu** 2024-05-28 13:45 UTC
