### ISSUE TITLE
Steam Deck gyro configuration does not work in first person view, and is unreliable during first person item use

### ISSUE THREAD

**Issue by SeedyZ** [Mr-Wiseguy/Zelda64Recomp#51] opened 2024-05-11 10:15 UTC
**Describe the bug**
After following the recommended configuration to enable gyro aiming on the Steam Deck, gyro controls do not reliably respond. Gyro aim does not work during C-Up first person, and is largely unreliable during first person item aiming (tested with Deku Bubble).

**To Reproduce**
1. Follow the binding recommendations from section [How do I set up gyro aiming on Steam Deck?](https://github.com/Mr-Wiseguy/Zelda64Recomp?tab=readme-ov-file#how-do-i-set-up-gyro-aiming-on-steam-deck)
2. Return in game and go into C-Up first-person view. The camera does not follow any movement of the gyro.
3. Equip Deku Mask and aim a bubble shot with gyro. The camera does not follow gyro movement. If it does follow gyro movement, tapping the analog stick disables further gyro aiming.

**Expected behavior**
The camera should move along with the gyro's movement in C-Up first person view. The camera should reliably follow gyro movement during first person item use.

**Screenshots**
Gyro has been configured to always be on:
![steam deck gyro always on](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/91563615/2cb35d00-e0ab-4cfe-8685-915bced44617)
Controls have been configured as recommended in setup guide:
![steam deck control binding](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/91563615/f01ace13-8cb7-4e5d-beff-26c1488923ca)

**Desktop (please complete the following information):**
 - OS: Linux / Steam Deck
 - Version: 1.0.0
 - CPU: AMD Ryzen
 - GPU: AMD Ryzen APU

**Additional context**
After following the recommended configuration for gyro aiming on Steam Deck, I had no luck getting gyro aim to work. After an hour of trying different settings tweaks including

* Gyro configuration in Steam mapping set as Mouse
* Gyro configuration in Steam mapping set as Gyro To Mouse [Beta]
* Changing gyro sensitivity within Recompilation
* Changing mouse sensitivity within Recompilation

The gyro aim suddenly worked while using the Deku Bubble after going back to the recommended configuration. I found with further testing that if gyro aim did work, afterwards using the analog stick to aim would disable gyro aiming, and I could not aim with it anymore. It isn't clear why this happens, so I can't tell if the problem lies with how Recompilation is reading inputs, or if it's a configuration issue based on Steam's controller mapping.

**Comment by Tau5** [comment] 2024-05-14 10:20
Wouldn't it be better to use [SteamDeckGyroDSU](https://github.com/kmicki/SteamDeckGyroDSU) to get the gyro input? Or at least use it as an option

**Comment by Mr-Wiseguy** [comment] 2024-06-11 04:08
Closing as multiple of us haven't been able to reproduce this issue on our Steam Decks and because #293 covers C-Up view not currently working with gyro/mouse aim. The analog stick causing gyro to stop working sounds like a configuration issue, so I'd double check that no steps were missed from the Steam Deck gyro setup guide and that your Steam Deck's OS is up to date. If you still can't get it to work then feel free to reopen.

**Closed as completed by Mr-Wiseguy** 2024-06-11 04:08 UTC
