### ISSUE TITLE
[Feature Request] Cutscenes aspect ratio correction

### ISSUE THREAD

**Issue by ClearStrelok** [Mr-Wiseguy/Zelda64Recomp#63] opened 2024-05-11 15:27 UTC
Majora's Mask presents its cutscenes in widescreen within the original 4:3 image, as pictured below: 

![Untitled-1](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/38838369/c230d2d3-b9bd-4151-9b9d-c6a57485ebd9)

Using the expanded aspect ratio option instead has them displayed in 21:9 (when playing in 16:9), which changes the original framing and displays things that shouldn't be seen, leading to one of the currently listed known issues with widescreen support: 

![Desktop_2024_05_11_16_55_08_251](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/38838369/485c803d-dfb0-4632-bc6e-f45f7131388e)

Ideally, I think cutscenes should always be displayed within a full 16:9 frame that matches the original aspect ratio, with either vertical or horizontal letterboxing added for 4:3 and 21:9 resolutions (This is the way the Halo Master Chief Collection team [addressed the longstanding FOV/letterboxing issues with Combat Evolved cutscenes](https://p20.zdusercontent.com/attachment/9046181/OcyXXkQv6IQWlD2brULIote9e?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..0-W5HomU6g1LtBtlR7UWhQ.eYLX5B3ruXzLSLlF0LCOjh_UofnejlZo5H-4OFX5nHaJAapWL38kWcs3wVgUCjHbAvLAYCwESnHqK3nYZROoPweDkR85z8UKUQA4cW9OFHyIOejZRZYXWNhpMQtZCvDwIRR-k7WKI8Tam0hgojsAEEtcsTitOCBMi7ZPVurpq4Z64m0loNQxo-kDX2oUginu0SrtxMK5Gq6vI1bDrBnrXbLr5-oQb3MYCd13u_WzZAa6EH-KPqHW6yt3UdpJsPc4A_eBSRAZiuZHnxRRDkbfu3AheFaOIBwF9S7TWa_YxWedcvT4QGB5KI4B-LqoUKDI.-DJKSpvV-7wrqMi0HeLWjQ) somewhere around 2020, although they later reverted it for unknown reasons).

This would result in an accurate fullscreen presentation of the cutscenes in 16:9, while preventing any potential issues with animations for ultrawide resolutions: (although I'm guessing ultrawide users would wish for the letterboxing to be optional) 

![Untitled-2](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/38838369/1df328e9-6fc1-4d31-9e8e-e0b2b5787237)

**Comment by ArhumMK** [comment] 2024-05-11 16:14
I second this, there are many games out there where the widescreen patch just expands the viewing area when the original game itself presented the cutscenes letterboxed to 16:9 within a 4:3 display. An option for this would be greatly appreciated and games that do widescreen cutscenes like this (Such as MGS2/3 HD collection) shows great results. The same for OOT and MM would work flawlessly (and also fix the issue of camera clipping out of bounds in some instances).

**Comment by SonicRay100** [comment] 2024-05-27 11:22
Just a note, there are sometimes off-screen assets in cutscenes that you can see if you use an expanded aspect ratio. I've detailed this in issue #255.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 03:30
Closing as duplicate of #360, since the latter has more info on it at this point.

**Closed as completed by Mr-Wiseguy** 2024-06-11 03:30 UTC
