### ISSUE TITLE
[Feature Request] Add compatibility for Italian localization patch ( MD5 checksum 80ed92035cb2b576344801e604ce0720 )

### ISSUE THREAD

**Issue by TedMosly** [Mr-Wiseguy/Zelda64Recomp#196] opened 2024-05-19 10:24 UTC
At the moment i can't play Majora Mask with Italian localization patch made by [Rulesless](https://drive.google.com/file/d/1tQf5gnX10PIiJq3_mG1dUWmt7XSMrUCp/edit). Can you made your tool compatible also with italian localization please?

Here the email contact for for contact the patch developer:

ruleless@tin.it

Game MD5 cheksum with italian patch applied:

80ed92035cb2b576344801e604ce0720

Original USA checksum:

b0cc37a45bc1b6c76cd7f0b71fe2bb1f

Thank you!

**Comment by Reonu** [comment] 2024-05-19 10:37
Thanks for your issue.

Multilanguage support is planned, but it won't involve using different ROMs. Rather, multilanguage support will be a part of the project itself.

Closing as duplicate of #97

**Closed as completed by Reonu** 2024-05-19 10:37 UTC

**Comment by TedMosly** [comment] 2024-05-19 10:41
Majora Mask and Ocarina of TIme are not been published in Italy so there is no official version in Italian.

**Comment by TedMosly** [comment] 2024-05-19 10:43
> Majora Mask and Ocarina of TIme are not been published in Italy so there is no official version in Italian.



> Thanks for your issue.
> 
> Multilanguage support is planned, but it won't involve using different ROMs. Rather, multilanguage support will be a part of the project itself.
> 
> Closing as duplicate of #97



> Thanks for your issue.
> 
> Multilanguage support is planned, but it won't involve using different ROMs. Rather, multilanguage support will be a part of the project itself.
> 
> Closing as duplicate of #97


Majora Mask and Ocarina of TIme are not been published in Italy so there is no official version in Italian.

**Comment by Reonu** [comment] 2024-05-19 10:44
> Majora Mask and Ocarina of TIme are not been published in Italy so there is no official version in Italian.

I know. Same with OoT not having a Spanish translation, and I'll be in charge of OoT having a Spanish translation, for example.

The plan is for multilanguage support to allow for fan translations. Don't worry. We'll have more details as the feature is closer to release; other things are much bigger priorities right now.
