### ISSUE TITLE
[Feature Request] Original dithering + dither filter

### ISSUE THREAD

**Issue by OpenRift412** [Mr-Wiseguy/Zelda64Recomp#140] opened 2024-05-14 19:21 UTC
I think something that would be good for emulating that original experience is restoring some of the dither effects and dither filter + blur effects that the original N64 uses as an optional toggle.

**Comment by Reonu** [comment] 2024-05-15 07:21
Closing as duplicate of #123

**Closed as completed by Reonu** 2024-05-15 07:21 UTC
