### ISSUE TITLE
The Windows executable wont launch!

### ISSUE THREAD

**Issue by drawaregit** [Mr-Wiseguy/Zelda64Recomp#56] opened 2024-05-11 13:20 UTC
**Describe the bug**
When i try to launch the .exe file, a windows pops-up and close a few seconds later.

**To Reproduce**
1. Open the file Zelda64Recompiled.exe

**Expected behavior**
Having the launcher pop up i guess?

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/129101277/288794ad-461b-47f1-8427-c1e223e99677)

**Desktop (please complete the following information):**
 - OS: [Windows 10](Sandbox mode for testing)
 - Version: [2004]
 - CPU: [Intel Core i7 8850H]
 - GPU: [No gpu in the Sandbox but i have a Nvidia Quadro P2000]

**Additional context**
Trying to launch the executable from a sandbox.

**Comment by Ammako** [comment] 2024-05-11 13:41
Without dedicated gpu, it would probably be trying to use intel, which I'm not surprised if it doesn't work.

**Comment by AQDuck97** [comment] 2024-05-11 15:24
I think this is the same problem as #54 
Try launch it from terminal/CMD and see if that gets it going, might need a couple tries

**Comment by Ammako** [comment] 2024-05-11 16:37
Yours is Linux, this is Windows. It's known that the Linux build has incompatibilities with various distros unless you build it for yourself.

**Comment by AQDuck97** [comment] 2024-05-11 18:46
> Yours is Linux, this is Windows. It's known that the Linux build has incompatibilities with various distros unless you build it for yourself.

As mentioned in that issue it's inconsistent if it crashes or not, and when it stops working it's the same symptom as this, so I don't think this is distro/Linux related (especially since it happens on Arch, generally that's the last distro to have issues like this where it sometimes work and sometimes doesn't on the same system)

**Comment by Darthagnon** [comment] 2024-05-11 22:05
I'm seeing the same issue.

Win10 v1709, Nvidia GTX 1060 MaxQ / Intel HD 630 / Intel i7-7700HQ

Executable starts and crashes immediately.

Windows error log from Event Viewer:
```
Faulting application name: Zelda64Recompiled.exe, version: 0.0.0.0, time stamp: 0x663da193
Faulting module name: ucrtbase.dll, version: 10.0.16299.820, time stamp: 0xe26f28c3
Exception code: 0xc0000409
Fault offset: 0x000000000006b64e
Faulting process id: 0x46b4
Faulting application start time: 0x01daa3ef73409701
Faulting application path: D:\Users\Darthagnon\Downloads\Zelda Majora's Mask PC Recompiled\Zelda64Recompiled-v1.0.0-Windows\Zelda64Recompiled.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 0e823352-19e5-4a9d-9dfc-c360a46c21ba
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Darthagnon** [comment] 2024-05-11 22:10
Related: #50, #43, #34

**Comment by Ammako** [comment] 2024-05-11 22:17
> I'm seeing the same issue.
> 
> Win10 v1709, Nvidia GTX 1060 MaxQ / Intel HD 630 / Intel i7-7700HQ
> 
> Executable starts and crashes immediately.
> 
> Windows error log from Event Viewer:
> 
> ```
> Faulting application name: Zelda64Recompiled.exe, version: 0.0.0.0, time stamp: 0x663da193
> Faulting module name: ucrtbase.dll, version: 10.0.16299.820, time stamp: 0xe26f28c3
> Exception code: 0xc0000409
> Fault offset: 0x000000000006b64e
> Faulting process id: 0x46b4
> Faulting application start time: 0x01daa3ef73409701
> Faulting application path: D:\Users\Darthagnon\Downloads\Zelda Majora's Mask PC Recompiled\Zelda64Recompiled-v1.0.0-Windows\Zelda64Recompiled.exe
> Faulting module path: C:\Windows\System32\ucrtbase.dll
> Report Id: 0e823352-19e5-4a9d-9dfc-c360a46c21ba
> Faulting package full name: 
> Faulting package-relative application ID: 
> ```

0xc0000409 is stack buffer overrun which isnt immediately clear what's actually the cause. Is there a second error just below it which may show the output from the application error log? (Unhandled exception error)

**Comment by Darthagnon** [comment] 2024-05-12 16:30
There are no other errors, only a string of 0xc0000409, one for each time I tried to run the EXE. Only thing that varies is Faulting process ID and faulting application start time.

**Comment by raphaelko62** [comment] 2024-05-13 10:19
having the same issue here too (my graphics card or IGPU is an intel hd graphics 5500), apparently a similar thing happened in issue #25 and the fix was "updating your drivers". problem is: i checked the intel website and there weren't any new drivers for me to download so i assume we're gonna have to wait for an update that adds support for more graphics cards in the future.

**Comment by JashKetchup** [comment] 2024-05-13 11:42
Same issue here - i5 6600k with GTX 1080 WIN 10 - all drivers have been updated, but pop-up always crashes

**Comment by Ammako** [comment] 2024-05-13 11:44
> Same issue here - i5 6600k with GTX 1080 - all drivers have been updated, but pop-up always crashes

But what version of Windows 10/11?

**Comment by JashKetchup** [comment] 2024-05-13 11:45
> > Same issue here - i5 6600k with GTX 1080 - all drivers have been updated, but pop-up always crashes
> 
> But what version of Windows 10/11?

Win10, edited my comment

**Comment by Ammako** [comment] 2024-05-13 11:50
No I mean, what version of Windows 10?

https://en.wikipedia.org/wiki/Windows_10_version_history#Channels

Because so far, the people I've seen for who it's not working are running outdated  and unsupported OSes. If we can figure out what the actual minimum required OS is, then it could be added to the system requirements (and then maybe later support for older versions might be added, but I wouldn't count on it.)

**Comment by JashKetchup** [comment] 2024-05-13 15:54
> No I mean, what version of Windows 10?
> 
> https://en.wikipedia.org/wiki/Windows_10_version_history#Channels
> 
> Because so far, the people I've seen for who it's not working are running outdated and unsupported OSes. If we can figure out what the actual minimum required OS is, then it could be added to the system requirements (and then maybe later support for older versions might be added, but I wouldn't count on it.)

Sorry for the confusion. Apparently I had an older build of Windows 10. I updated to the last update available, version 21H2 , and the issue of the pop-up crashing was solved. I was curious to find my previous version, causing me to accidentally recover back to my previous version, which is Version 1909 (OS Build 18363.1556). So for anyone with an older build of Windows, I’d recommend to update to the latest

**Comment by raphaelko62** [comment] 2024-05-13 16:09
that's pretty weird because my own machine says it's on "version 22H2". and it's been like that for a while. unless its something with the update names (i'm currently checking for updates but it looks like it's gonna take a bit) i might have to downgrade or wait for a patch
update: i checked the update menu and there's no mention of "21H2" anywhere. i assume that there are different windows versions for different types of computers, and my laptop's 22H2 version isn't yet compatible with the program. i'll post another update if i find anything important
update: it looks like JashKetchup might need to update again; i checked the wikipedia link Ammako posted, and it's not at all a "different computer different version" thing. 22H2 is actually the latest version and even there, the program doesn't launch.

**Comment by Ammako** [comment] 2024-05-13 16:11
22H2 is the latest, I'm not sure why some people might not be getting it.

**Comment by raphaelko62** [comment] 2024-05-13 16:18
> 22H2 is the latest, I'm not sure why some people might not be getting it.

what's even weirder is that the program becomes incompatible again in 22H2. personally i'm just gonna wait for a patch to the recomp that fixes this. for now i'll exit this thread because i don't really know a whole lot about OS versions nor do i know WHAT's making it crash on 22H2

**Comment by Ammako** [comment] 2024-05-13 16:19
I'm not sure it's a 22H2 incompatibility, in your case I think Intel HD 5500 may just be too old.

**Comment by JashKetchup** [comment] 2024-05-13 17:08
> that's pretty weird because my own machine says it's on "version 22H2". and it's been like that for a while. unless its something with the update names (i'm currently checking for updates but it looks like it's gonna take a bit) i might have to downgrade or wait for a patch update: i checked the update menu and there's no mention of "21H2" anywhere. i assume that there are different windows versions for different types of computers, and my laptop's 22H2 version isn't yet compatible with the program. i'll post another update if i find anything important update: it looks like JashKetchup might need to update again; i checked the wikipedia link Ammako posted, and it's not at all a "different computer different version" thing. 22H2 is actually the latest version and even there, the program doesn't launch.

My bad and sorry for the confusion; somehow I read 21H2 somewhere, but I just double checked and my version is in fact 22H2. Opening the .exe on this version works as expected on my end.

**Comment by raphaelko62** [comment] 2024-05-13 19:27
oh. thanks for you two's input. i guess i'm gonna have to wait for the Harbour Masters port of mm and i DID hear that the specs requirements to run recomps are a bit higher than normal pc ports.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 21:04
If you have no GPU in the sandbox environment then this won't run for obvious reasons. Closing this issue.

**Closed as not planned by Mr-Wiseguy** 2024-06-11 21:04 UTC
