### ISSUE TITLE
[Feature Request] Native macOS Build 

### ISSUE THREAD

**Issue by AarnavSin** [Mr-Wiseguy/Zelda64Recomp#141] opened 2024-05-14 20:21 UTC
I think a native macOS build would be great for a project like this! Lots of Mac players would wanna play this iteration.

**Comment by zroes** [comment] 2024-05-14 20:45
I was going to make the same request. The Windows version doesn't appear to work in Parallels, and I was hoping a Mac version was in the works.

**Comment by DarioSamo** [comment] 2024-05-14 22:53
The biggest hurdle to a Mac port is the [lack of a Metal backend on RT64](https://github.com/rt64/rt64/issues/6#issuecomment-2106382071) as I don't have the hardware to develop one myself. However, a few people are already attempting to implement one so you can follow the progress there.

**Comment by Reonu** [comment] 2024-05-14 22:56
Closing as duplicate of #66

**Closed as not planned** 2024-05-14 22:56 UTC
