### ISSUE TITLE
Window Size Eclipses Monitor Size

### ISSUE THREAD

**Issue by WishThePone95** [Mr-Wiseguy/Zelda64Recomp#100] opened 2024-05-12 16:10 UTC
When I start the game the window size is too big, I can't find an option to resize the window so I'm assuming there is no way to do so.

The problem persists every time I open the application, not everybody has a 4K PC my screen res is 1360 x 768

When I opened it I had hoped it would scale properly.

**My Desktop Info:**
 - OS: Windows 10 Professional
 - CPU: AMD Ryzen 5600G
 - GPU: NVIDIA GeForce 1050 TI
 - 32GB Ram

**Comment by Calinou** [comment] 2024-05-12 19:44
As a workaround, use https://github.com/Codeusa/Borderless-Gaming so that the window is set to your screen size regardless of its original size. (You can find a free release here: https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5.6)

**Comment by bryc** [comment] 2024-05-13 01:16
Already reported this issue - you need to check the existing issues before making one.

Just press F11, it will fix for some reason, and then the settings will be saved.

**Comment by Calinou** [comment] 2024-05-13 01:30
- Duplicate of https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/40.

**Comment by Mr-Wiseguy** [comment] 2024-06-11 04:11
Closing as duplicate of #40 as stated.

**Closed as completed by Mr-Wiseguy** 2024-06-11 04:11 UTC
