### ISSUE TITLE
[Feature Request] Launch straight into game with command line argument.

### ISSUE THREAD

**Issue by t0mtee** [Mr-Wiseguy/Zelda64Recomp#479] opened 2024-09-05 15:34 UTC
For example, using `-mm` would launch straight into Majora's Mask, and when OoT becomes available `-oot` will launch straight into Ocarina of Time. Would be useful to have for game launchers such as Playnite.

**Comment by Reonu** [comment] 2024-09-14 10:37
Closing as duplicate of #161

**Closed as completed by Reonu** 2024-09-14 10:37 UTC

**Comment by t0mtee** [comment] 2024-09-14 19:47
Apologies, completely missed it
