### ISSUE TITLE
Missing film grain/noise effect

### ISSUE THREAD

**Issue by mntorankusu** [Mr-Wiseguy/Zelda64Recomp#123] opened 2024-05-13 18:34 UTC
On N64, the scenes in Majora's Mask with motion blur also appear to have a film grain effect. I'm not sure if it's an additional effect or if it's just a part of how the motion blur itself works. The Angrylion and ParaLLEl RDP plugins are able to correctly produce the grainy look in emulators, so I've attached some screenshots for comparison. The Nintendo Switch Online emulator also reproduces the film grain effect, but I don't have a clean screenshot, so it's a bit hard to see here.

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/13548364/5eef58b9-bc20-4e4f-8755-a45a9e078113)
Screenshot of Retroarch Mupen with ParaLLEl-RDP showing film grain effect

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/13548364/39bf7f74-a51e-49ee-a955-802341650fa3)
Similar shot from the opening using Zelda64Recomp showing no film grain

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/13548364/96ed037c-0d6b-4404-893b-36773124cae1)
Screenshot of a YouTube video featuring the Nintendo Switch Online version also showing a film grain effect

I love the grainy, gritty look of the original, so I'd love to see it reproduced faithfully in Zelda64Recomp.

**Comment by FSR-1** [comment] 2024-05-13 18:57
you sure this isnt just a side effect of an emulator they are not 100% accurate but if you did find an inaccuracy nice find
EDIT: wait nvm you said that the emulators are able to correctly produce it mb

**Comment by aroenai** [comment] 2024-05-14 04:51
Just to add, this effect is supposed to display as random noise for the floating masks when falling down onto the first Deku flower and in the grey scale filter for the Zelda memory as well.

**Comment by DarioSamo** [comment] 2024-05-14 12:46
There's no actual way to reproduce this accurately outside of Angrylion/ParaLLEl due to the lack of programmable blending in GPUs. On top of that, color dithering (which is used here with the noise pattern) doesn't apply to 32-bit framebuffer output which is what the renderer upgrades it to, and the noise is applied on the dithering step. Basically, dithering is only relevant when converting from full color precision to 16-bit.

If you see this effect outside of the two renderers I mentioned, it is basically done for artistic purposes as a workaround. Even so, the end result will most likely end up much weaker due to the dithering being applied on fragment shader output and not on blending.

The proper solution would be for the project to just upgrade the effect to have a noise effect done through other means and not rely on the dithering to do so, as it'd affect the expected output of other games where it may not be intended.

**Comment by s-ilent** [comment] 2024-05-15 07:53
> On top of that, color dithering (which is used here with the noise pattern) doesn't apply to 32-bit framebuffer output which is what the renderer upgrades it to, and the noise is applied on the dithering step. Basically, dithering is only relevant when converting from full color precision to 16-bit.

This seems factually incorrect, if I'm following you right. Banding is a rather noticeable problem on any 8-bit-per-colour display with a wide enough gradient. [This is an old problem](https://loopit.dk/banding_in_games.pdf), one that [even affects 30-bit colour output](https://gpuopen.com/wp-content/uploads/2016/03/GdcVdrLottes.pdf). While it seems like it'd be less relevant on an old game like this which isn't rendering to a floating point buffer or anything, at high resolutions like 4K you're stretching the gradients between even individual texels [pretty wide](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16026653/3440f04c-2706-43b9-8af6-742ddaa115ea). 

I'm curious whether adding pre-quantization noise for dithering would result in a similar noise effect to the original as posted.

**Comment by DarioSamo** [comment] 2024-05-15 12:06
> This seems factually incorrect, if I'm following you right. Banding is a rather noticeable problem on any 8-bit-per-colour display with a wide enough gradient.

Yes, but I'm talking specifically about what N64 does. The console supports output in 32-bit mode, and the RGB dithering is not applied on that mode. Safe to say, if you applied it in this case anyway, the effect would be pretty much unnoticeable from what the OP wants.

**Comment by mntorankusu** [comment] 2024-05-15 14:19
Of course, it doesn't really matter how the effect is achieved. If it's difficult to do it in exactly the same way as the original, then a shader that gives a nice, comparable noise effect would be fine.

**Comment by mntorankusu** [comment] 2024-05-15 15:35
The intro shows a gray screen with the noise filter applied, which is probably the most helpful thing that it could give us to see what is happening visually: 
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/13548364/585f8b7f-9e2a-4027-b99e-f3a63d5ccbd6)

It looks like a simple random noise filter applied to each color channel individually. A shader that randomly varies each subpixel by +-3% would look very similar.

**Comment by BilonFullHDemon** [comment] 2024-05-17 10:16
I think that's dithering effect

**Comment by DarioSamo** [comment] 2024-05-18 16:40
> It looks like a simple random noise filter applied to each color channel individually. A shader that randomly varies each subpixel by +-3% would look very similar.

Sorry, was unable to get back to you on this due to external reasons. You're pretty much right that would achieve a fairly close approximation because this is how it works:
- Color is computed internally in full precision.
- Blender drops the result to 16-bit, but before dropping the value, a random value between 0-7 (255 being the full range) is added. This is a hardware dithering capability of the console that is completely disabled when using 32-bit output.

The main reason why RT64 can't and is unlikely to do this is that it happens _after_ blending, something we can't accurately reimplement without programmable hardware blending. If you've followed along, that means that even if you draw something on top with 1% alpha transparency it'll have a very strong noise effect regardless, which is why it can't be done on the shader output stage.

7/255 is pretty much indeed around 3% or less of the amount of the color variation. If Recomp adds a noise filter with that much strength after the effect is drawn (post-blending), then you'd get a pretty accurate recreation.

**Comment by DarioSamo** [comment] 2024-05-24 21:57
I have an update on this.

> something we can't accurately reimplement without programmable hardware blending

I had a thought on how to do this and gave it a shot. As this is a post-blending operation, if the conditions are right, it is actually possible to do a really good approximation of this by just redrawing the triangles and change the pipeline to an additive noise effect to replicate the particular noise dithering mode and do it post-blending.

The results are pretty good!
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/538504/e6e7fe02-8e61-4929-a84c-62f2dd875798)

I'll be adding this in the next update.

**Comment by Reonu** [comment] 2024-05-26 12:26
Fixed by #252

**Closed as completed by Reonu** 2024-05-26 12:26 UTC
