### ISSUE TITLE
PAL Support

### ISSUE THREAD

**Issue by JustJeff88** [Mr-Wiseguy/Zelda64Recomp#516] opened 2024-12-12 21:01 UTC
I was wondering if it would be possible to support the PAL version of this game (and OoT, in the future). I would like to play the game in my native French, and it would open up the game to German and Spanish speakers as well. The other port of OoT only uses EU roms and they extended support of the Perfect Dark port when myself and several others asked for PAL and JPN support, so I wanted to ask.

**Comment by Mr-Wiseguy** [comment] 2024-12-19 16:35
Duplicate of #97. This will be added either via translation mods being made after modding support is out in the 1.2 release, or as a dedicated feature in a future release. It's already in the planned features list in the readme.

**Closed as completed by Mr-Wiseguy** 2024-12-19 16:35 UTC
