### ISSUE TITLE
[Bug] Issues with Vulkan under Linux with Intel Iris Graphics

### ISSUE THREAD

**Issue by Lestlandia** [Mr-Wiseguy/Zelda64Recomp#332] opened 2024-05-31 14:41 UTC
ispci output for drivers: 
VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
        DeviceName: Onboard - Video
        Subsystem: Intel Corporation Iris Plus Graphics G7
        Kernel driver in use: i915

Issue will not happen on OG Hardware.

Gameplay is normal up until the encounter with skull kid after being transformed into deku link and the gate is closed. Sometimes in other parts of gameplay the same issue may occur, but its always in cutscenes. Video feedback will freeze, but audio will continue playing as if game is still running despite that.

1. Turn file into executable and Launch Zelda64Recompiled in the terminal (" sudo chmod +x Zelda64Recompiled; ./Zelda64Recompiled)
2. Play the first section of the game up to the cutscene Tael is being cut off from his sister
3. Video feedback will freeze. Terminal Output (vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.)

**Expected behavior**
Video will continue as normal, gameplay is not impeeded, Inputs still work.

**Screenshots**
![ZeldaRecompiledIssues](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/101432943/04a2cc51-7123-44fe-b08a-f2dae1f992cb)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu/KDE Plasma; x11 [Kubuntu])
 - Version: 24.04 (Kernel: 6.0.0-31 generic)
 - CPU: Intel Core i5-1035G7 (Quad-Core, 8 Threads 1,20 GHz - 3,70 GHz)
 - GPU: Intel Iris Plus Graphics G7
 - GPU driver: i915 (DRM)
 - System: GPD Win Max (2021)

**Additional context**
This may be due to issues related to still yet inadequate Intel Graphics support or aged hardware, i know that it doesnt run properly under Intel GPUs as of yet. However i opted to post this regardless to aid in development. 
In case its not related to either, please get in contact with me, to see if i can provide some aid and more information.

**EDIT**
If this includes an option to run under OpenGL i would attempt to see if it runs fine there.

**Comment by Mr-Wiseguy** [comment] 2024-06-03 20:49
Thanks for the report. Like you mentioned, this is the same known Intel GPU issue under Linux that the readme mentions. Apparently there's a chance it was solved in a recent driver update as discussed [here](https://github.com/Zelda64Recomp/Zelda64Recomp/issues/28#issuecomment-2144042802), would you be able to update your drivers and check if it's resolved?

**Comment by Mr-Wiseguy** [comment] 2024-06-11 05:01
Closing as Intel Linux support is a known issue listed in the readme and because this is a duplicate of #28 (from https://github.com/Zelda64Recomp/Zelda64Recomp/issues/28#issuecomment-2118845262 onwards). If you do update your drivers, please let us know whether the issue was fixed.

**Closed as completed by Mr-Wiseguy** 2024-06-11 05:01 UTC
Labels: help wanted
