### ISSUE TITLE
[Feature Request] - Import and export game save data as .fla file for use in emulators

### ISSUE THREAD

**Issue by ripnetuk** [Mr-Wiseguy/Zelda64Recomp#374] opened 2024-06-06 09:42 UTC
It would be good if we could import and export .fla save game files, so we can play sections of the game that are too hard (Arrow competitions for example) on an emulator with cheats (like slowdown), then re-import the save to the superior Zelda64Recomp runtime.

At the moment they seem to be a 256k binary blob, which I cannot get to load in say PJ64

**Comment by Holby** [comment] 2024-06-06 20:00
You just need to swap the endianness of the .bin file, then it should work in an emulator.
https://github.com/Zelda64Recomp/Zelda64Recomp/issues/160#issuecomment-2153298099

**Comment by Mr-Wiseguy** [comment] 2024-06-11 04:56
Closing as duplicate of #160.

**Closed as completed by Mr-Wiseguy** 2024-06-11 04:56 UTC
