### ISSUE TITLE
[FEATURE REQUEST] Native Switch Support

### ISSUE THREAD

**Issue by DaRealCoolGamer2773** [Mr-Wiseguy/Zelda64Recomp#442] opened 2024-07-26 18:43 UTC
A port for modded Switches, do I need to say more?

**Comment by Mr-Wiseguy** [comment] 2024-07-26 18:46
Duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/334, there are no plans for this.

**Closed as completed by Mr-Wiseguy** 2024-07-26 18:46 UTC
