### ISSUE TITLE
[Request] VR Support, Mod Support, HD texture mods, and Custom Hud support, etc.

### ISSUE THREAD

**Issue by SsjSora** [Mr-Wiseguy/Zelda64Recomp#310] opened 2024-05-28 17:45 UTC
Hoping we can get some neat features SIMILAR to Ship of Harkanian, etc. Where we get the abilities to do what ever we want. Like for example. FULL MOD SUPPORT, Like adding custom 3D Models and such, would be really dope AF. If you ask me, install custom assets, HD text mods, like 3DS experience, etc. The ability to use HD texture packs like Nerrels Majora's Mask HD texture pack or a Majora's Mask ReLoaded SIMILAR to OoT ReLoaded, give us the ability to move to D-Pad to the far RIGHT of the screen, I would appreciate that. I play with the Pro Controller, and I PREFER to see the D-Pad on the right side of the screen. "I have a disability" "Eye problems" So its really hard for me to see the D-Pad on the far left of the screen. Sorry MrWiseGuy. T_T Also VR SUPPORT WOULD BE DOPE!!! I know we got Brian who made VR on Dolphin VR, but if we had actual VR Support on Zelda64Recomp. That would be a GAME CHANGER!!! For EVERYONE!!! Especially for VR Enthusiasts. Give us the abilities to spawn actors everywhere, Debug features, etc. Debug Camera, Allot of FUN THINGS! To do. Etc. Restore the SUNS song in the Game, would be neat. ^_^ Let us customize our HUD as much as we want. To make it look like a modern game, etc. I like Ship of Harkanian but I think I'm going to like Zelda64Recomp more. And HDR support as well would be nice. And a feature to send in bug logs so we can show what we're having problems with, etc. Can't wait to play this game on my 50" 4kTV! ^_^Hope to get OoT version soon. Hopefully Minishcap as well. Keep it up with the work! :3 Would love custom models, in the game too. :)

**Comment by Reonu** [comment] 2024-05-28 17:51
Mod, model replacement and HD texture support is planned, as stated in the readme. Pretty much everything you've asked for could be done when mod support arrives.

Closing as duplicate of #89

**Closed as completed by Reonu** 2024-05-28 17:51 UTC
