### ISSUE TITLE
[Question] Is MSAA intended to be configurable on Linux?

### ISSUE THREAD

**Issue by jfajardo5** [Mr-Wiseguy/Zelda64Recomp#153] opened 2024-05-15 15:52 UTC
![Screenshot_20240515_114934](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/24752213/76b38542-ffd7-4d6d-a8cc-5d85993fc810)

It's not available for me on my system.

**System info:**

Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.8.9-arch1-2 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C95
System Version: 1.0

**Comment by DarioSamo** [comment] 2024-05-15 16:27
It will work if your driver supports the feature it mentions there. As far as I understand a fix will come to Mesa to support this feature at some point, as the feature works on the Windows driver as intended on that hardware. There's no plans to provide a workaround at the moment.

**Comment by Reonu** [comment] 2024-05-15 16:39
Closing since this is a driver issue and not a recomp issue.

**Closed as completed** 2024-05-15 16:39 UTC

**Comment by jfajardo5** [comment] 2024-05-15 16:46
> It will work if your driver supports the feature it mentions there. As far as I understand a fix will come to Mesa to support this feature at some point, as the feature works on the Windows driver as intended on that hardware. There's no plans to provide a workaround at the moment.

Thank you for the info!
