### ISSUE TITLE
[Feature Request] Addition of an Input Selection.

### ISSUE THREAD

**Issue by RyouFuchiKyou** [Mr-Wiseguy/Zelda64Recomp#55] opened 2024-05-11 12:57 UTC
As noted in this [thread](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/41), the Nintendo Switch Online N64 Controller has binding issues, and without a method to select input, it seems this recomp ignores what controller you want to use for it.

**Comment by Ammako** [comment] 2024-05-11 16:52
atm the problem isn't that you can't input XInput back button, it's that the program is hardcoded to use that button to open the in-game menu. An option to remap the Menu button will be added in an update and this should solve the problem.

#24

**Comment by Mr-Wiseguy** [comment] 2024-06-11 03:25
Closing this as remapping the menu button was added in 1.1.0, which should allow NSO N64 controllers to be used by binding that to a different button.

**Closed as completed by Mr-Wiseguy** 2024-06-11 03:25 UTC
