### ISSUE TITLE
Colorful "streaks" across flat animated textures

### ISSUE THREAD

**Issue by CausalityViolation** [Mr-Wiseguy/Zelda64Recomp#318] opened 2024-05-29 18:56 UTC
When starting the game the startup screen is covered in colorful lines. They seem to be random, but appear every time the game starts. 
After starting a game the lines only appear on "flat" animated things like Fairies, flames and other things. 
Tried messing around with all graphic settings but didn't change anything. 

 - OS: Windows 10,
 - Version: Latest available
 - CPU: Ryzen 5800x3d
 - GPU: 7900XT
 - GPU driver: AMD Driver version 24.5.1
![1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/80385721/c1046763-c63e-4620-acdd-62d26e2ec288)
![2](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/80385721/8e11ebf6-5805-4ce6-acaf-bf6497912b6c)

**Comment by Dreykoth** [comment] 2024-05-29 20:07
Playing on a ROG Ally, and I'm also having this issue.(CPU: AMD Ryzen Z1 + integrated). however I downloaded the recomp to my main pc. (CPU: R5 3500, GPU: 3060) and the issue is non-existent. although the main menu screen has the same weird static.

maybe an AMD issue with the new update?

**Comment by Mr-Wiseguy** [comment] 2024-05-29 21:26
Duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/289, this is an RDNA3 driver bug with the framebuffer format that recomp uses in the latest update to allow for high framerate motion blur. There are workarounds listed in that issue.

**Closed as completed by Mr-Wiseguy** 2024-05-29 21:26 UTC
