### ISSUE TITLE
not a bug but translation issue

### ISSUE THREAD

**Issue by SosPosos** [Mr-Wiseguy/Zelda64Recomp#104] opened 2024-05-12 18:23 UTC
is there any way to make ntsc-u rom with translation patch work?

**Comment by Mr-Wiseguy** [comment] 2024-05-14 13:51
Duplicate of https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/90, multilang support will be a feature of this project itself in the future and not rely on needing a different ROM for them.

**Closed as completed by Mr-Wiseguy** 2024-05-14 13:51 UTC
