### ISSUE TITLE
Mapping C right on official Switch N64 controller doesn't work

### ISSUE THREAD

**Issue by FlumSM** [Mr-Wiseguy/Zelda64Recomp#74] opened 2024-05-11 20:25 UTC
Pressing C right opens the menu. Trying to map C right cancels out and closes the menu.

https://www.youtube.com/watch?v=P6HsMEtEGbQ

**Comment by Steifl** [comment] 2024-05-11 22:50
I can confirm this, having the same issue. Using the Nintendo Switch Online N64  Controller, pressing the C right button will open the menu and cannot be assigned to the ingame C right button. I assume this is because the C right button on the N64 Controller is being registered as the Select Button from the XBox One Controller when pressed (can be seen in Steam Configuration -> Controller -> Begin Test.)

Just realized this issue is also described in #41 

EDIT#2
Found another issue related to this in #24

**Comment by KahlebMcMurtrie** [comment] 2024-05-11 23:52
I'm running into this exact issue too 😭
there's no way for me to remap the NSO N64 controller right C button either because it toggles the menu. Temporarily gonna use my Pro Controller but I hope this gets resolved soon! Godspeed y'all ✨

**Comment by GoldUltima** [comment] 2024-05-12 06:42
Can confirm. Can't map right C since it toggles the menu, making the controller useless. Also, I think there may be a dead zone issue because even when I map it to other buttons I still fail the song tutorials

**Comment by Ammako** [comment] 2024-05-12 12:41
It's already known and acknowledged, and will be fixed by allowing to remap the menu button.

**Comment by m9henri** [comment] 2024-05-12 13:19
i have this issue too. can someone maybe notify me (i dont know much bout github and if thats possible) when this issue getss resolved

**Comment by Deozaan** [comment] 2024-05-15 23:09
If you use Steam Input to remap the N64 inputs, you can work around this issue for now. I described how I did it here: https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/41#issuecomment-2113602254

**Comment by Reonu** [comment] 2024-05-19 22:24
Known issue being tracked in  #41, will be fixed soon

**Closed as completed by Reonu** 2024-05-19 22:24 UTC

**Comment by zzzTNTzzz** [comment] 2024-05-21 03:54
Yeah im having the same problem C-right opens up menu please fix
