### ISSUE TITLE
[HD Texture Branch] Crash when entering the Mighty Training Center

### ISSUE THREAD

**Issue by Antorboy** [Mr-Wiseguy/Zelda64Recomp#430] opened 2024-07-06 16:35 UTC
**Describe the bug**
Whenever you enter the Training Center, the game close.

**To Reproduce**
See the joint video, no settings has been changed, except for controls.

**Expected behavior**
Not crash and be inside the Training Center and play the mini game, i guess?

**Screenshots**
https://github.com/Zelda64Recomp/Zelda64Recomp/assets/53264039/de60b958-5b25-45c7-8e05-4cd19cb9860b

**Desktop:**
 - OS: Windows 11
 - App Version: 1.1.1
 - CPU: AMD Ryzen 5 3600 6-core
 - GPU: NVIDIA GeForce GTX 1660 Ti
 - GPU driver: GeForce Game Ready Driver 556.12

**Comment by Mr-Wiseguy** [comment] 2024-07-06 16:42
Thanks for the report. We're unable to reproduce this issue, could you confirm whether you're playing on the 1.1.1 build from the releases tab or one of the CI builds? If it's the former, could you try the latest CI build from [here](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9815401418) and see if it still happens?

Additionally, would you be able to collect a crash dump? There's a guide on how to enable them from Microsoft here: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by Mr-Wiseguy** [comment] 2024-07-06 16:43
Oh also, can you send your save file and config jsons?

**Comment by DarioSamo** [comment] 2024-07-10 15:31
I have a good reason to believe this is only a problem with the HD Textures PR and you might've forgotten to include that very important detail in your report. It's the only branch I can reproduce the issue on. Can you confirm?

**Comment by Mr-Wiseguy** [comment] 2024-07-10 16:41
Confirmed that this only happens in the HD texture branch.

**Comment by DarioSamo** [comment] 2024-07-11 01:27
Fixed as of the latest commit in the HD Textures branch for RT64 (will be updated on Recomp's side later).

**Comment by Mr-Wiseguy** [comment] 2024-07-11 04:26
The HD textures branch has been updated with a fix for this.

**Closed as completed by Mr-Wiseguy** 2024-07-11 04:26 UTC
