### ISSUE TITLE
[Feature Request] Single-frame advance pause buffering

### ISSUE THREAD

**Issue by dwigginsd** [Mr-Wiseguy/Zelda64Recomp#302] opened 2024-05-28 00:55 UTC
Hi,

Due to the very low lag in this version, pause buffering for use with speed running tricks does not work well. Can you please implement the option to perform Single-frame advance pause buffering? Ship of harkinian has implemented this as a work around for this limitation.

Thank you!

**Comment by Bordraw** [comment] 2024-05-29 02:09
I think this is the kind of feature better suited to ship of harkinian than the recomp. Luckily they just released their Majora's Mask port: https://github.com/HarbourMasters/2ship2harkinian/releases/tag/1.0.0

**Comment by Mr-Wiseguy** [comment] 2024-06-11 22:32
Closing this as a duplicate of #72, this is something I would like to address as I explain there.

@Bordraw please don't make guesses on other peoples' issues as to which features will and won't be in this project.

**Closed as completed by Mr-Wiseguy** 2024-06-11 22:32 UTC

**Comment by Bordraw** [comment] 2024-06-14 18:31
I apologize, that was presumptuous of me
