### ISSUE TITLE
Uses integrated GPU, and not Dedicated GPU

### ISSUE THREAD

**Issue by cosaga** [Mr-Wiseguy/Zelda64Recomp#315] opened 2024-05-29 01:32 UTC
**Describe the bug**
Game uses my integrated GPU, rather than the dedicated GPU

**To Reproduce**
1. For me at least. Open Game
2. Check task manager and see integrated GPU at 90+%

**Expected behavior**
I would assume this to use the dedicated GPU if one was available, given the nature of some of the graphics options available.

**Screenshots**
Version 1.1 Graphics setting and task manager,
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/19290516/9af5696a-6f5c-423b-97de-c4be0974f4e1)

Version 1.0 Graphics setting and task manager, ![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/19290516/569d9bac-2201-493d-8ba6-7974f9fe5eb4)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (OS BUILD 22621.2715)
 - CPU: AMD 770X
 - GPU: AMD RX 5700 XT
 - GPU driver: AMD driver 24.1.1 then 24.5.1

**Additional context**
Well after upping to 1.1, I swear the game was more pixelated to me, so I checked my settings, and all looked the same. That is when I checked Task Manager to see exactly how my system was struggling. It was then I noticed my integrated GPU was rocking 90%+. I reverted back to 1.0 to see if the behavior was the same, and it was(side note the game was not more pixelated on 1.1, I was just crazy about that). I figured either this was a bug, or a massive oversite for the program to not prefer the dedicated GPU. At least it shows it is not a 1.1 specific issue; for my setup at least, I guess I cannot confirm if others have noticed this yet. I feel like if people had I could find somebody talking about the fact this does not use the best hardware available to the system. I did try rebooting, no luck. I will update my GPU drivers and try again, but I doubt it will. Oh and moments before posting this, but after I typed everything before this sentence. I told windows to use high performance with the exe, and the exe still uses the integrated GPU. Ok updated drivers did nothing. posting now

Also, I hope this is a bug, otherwise I kinda feel like an asshole for being the guy on the internet who says devs doing gods work are not doing a good enough job because their totally free amazing project doesn't work as good as it could in my opinion.

**Comment by Mr-Wiseguy** [comment] 2024-05-29 01:37
Thanks for the report, this is a known issue that is fixed and will be in the 1.1.1 release (duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/173). The root cause is pretty funny: because your iGPU (which is RDNA2) technically supports ray tracing but your discrete GPU (which is RDNA1) doesn't, RT64 accidentally considers your iGPU as the stronger of the two. The latest RT64 version fixes this issue, so recomp just has to update to it.

**Comment by Reonu** [comment] 2024-05-29 01:43
Hello!

I just created a PR that updates RT64 to fix this issue. If you want to play now without having to wait for 1.1.1, feel free to head [here](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/316/checks) and, once the artifacts finish building (should be around 5 minutes after me publishing this comment), go to where it says "Artifacts" and download the Windows artifact. This version should work correctly and pick up your dedicated GPU.

I hope you can enjoy the game now!

**Comment by cosaga** [comment] 2024-05-29 01:56
Holy crap ya'll reply fast. 

I feel bad for making a duplicate. I looked to confirm I wasn't....Obviously I did not double check good enough.

**Comment by Reonu** [comment] 2024-05-29 01:57
You can pay for your crime by playing the game and having a good time.

**Comment by cosaga** [comment] 2024-05-29 01:57
> I hope you can enjoy the game now!

Oh I was already, believe me!

**Closed as completed** 2024-05-29 21:36 UTC
