### ISSUE TITLE
[Bug] Z-Fighting in Knife Room when entering or leaving room.

### ISSUE THREAD

**Issue by DisplayGFX** [Mr-Wiseguy/Zelda64Recomp#339] opened 2024-06-02 11:35 UTC
In the latest public release (1.1.0)

## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**

551.61 - Just upgraded to 555.85 and seeing this bug as well

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

As far as I know, it does not, but its hard to verify without an original N64 console.
https://youtu.be/RSQzQ1m1AmQ?&t=645

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

Intended mechanics.

**Describe the bug**

There appears to be Z-Fighting on the rug and the peeled wallpaper.

**To Reproduce**
1. Go to Anju, get the Knife Room Key
2. Enter Knife Room

**Expected behavior**
No Z-Fighting, accurate to the ground truth.

**Screenshots**
![Zelda64Recompiled_ztKrN33VZO](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/128821719/66612fd4-6127-42f1-82d4-73cb864b92f6)

**Desktop (please complete the following information):**
from dxdiag
```
      Time of this report: 6/2/2024, 07:34:01
             Machine name: 7950X
               Machine Id: {7C58C963-20AF-4EC0-9067-239ACFCECFEF}
         Operating System: Windows 11 Pro 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: X670E AORUS MASTER
                     BIOS: F6 (type: UEFI)
                Processor: AMD Ryzen 9 7950X 16-Core Processor             (32 CPUs), ~4.5GHz
                   Memory: 65536MB RAM
      Available OS Memory: 64664MB RAM
                Page File: 25756MB used, 48123MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 288 DPI (300 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.5.5
           DxDiag Version: 10.00.22621.3527 64bit Unicode
```

**Comment by Reonu** [comment] 2024-06-02 12:07
This is accurate behaviour present on N64 hardware and also a duplicate of #254 .

You can see a video of the issue on Angrylion in the issue I linked. Wiseguy has verified that it happens on N64 too.

The video you linked is probably from Wii VC or some bad emulator that happens to avoid the "issue" by virtue of inaccuracies.

**Closed as completed** 2024-06-02 12:07 UTC

**Comment by DisplayGFX** [comment] 2024-06-03 03:24
My bad, I never recalled noticing it.
