### ISSUE TITLE
Please allow support for PAL (For multi language support)

### ISSUE THREAD

**Issue by Cecilithub** [Mr-Wiseguy/Zelda64Recomp#114] opened 2024-05-13 01:54 UTC
As of currently there is no way for me to play the game in my native toungue, please add support for PAL

**Comment by Optekah** [comment] 2024-05-13 05:24
Search for open issues before creating unnecessary duplicates.

**Comment by pheraph** [comment] 2024-05-13 07:08
Duplicate of #97

**Comment by Reonu** [comment] 2024-05-14 12:28
Closing as duplicate of #97.

**Closed as not planned** 2024-05-14 12:29 UTC
