### ISSUE TITLE
how to change rom

### ISSUE THREAD

**Issue by jefferson124** [Mr-Wiseguy/Zelda64Recomp#98] opened 2024-05-12 15:00 UTC
I need to test the program with another rom, however when I start the game I get the first rom that I put to decompile, what file should I delete? or how can I put another rom?

**Comment by JJihiro** [comment] 2024-05-12 15:12
Delete the folder appdata/local/Zelda64Recompiled.

**Comment by Mr-Wiseguy** [comment] 2024-05-14 13:50
Duplicate of https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/90

**Closed as completed by Mr-Wiseguy** 2024-05-14 13:50 UTC
