### ISSUE TITLE
Classic N64 USB Controller mapping issue

### ISSUE THREAD

**Issue by TrueHit** [Mr-Wiseguy/Zelda64Recomp#224] opened 2024-05-20 17:43 UTC
https://www.amazon.com/Classic-Controller-iNNEXT-Joystick-Raspberry/dp/B07449HLKJ

Unable to map over the physical C button Right. This button is used to open/close the general/controls/graphics/sounds settings.

Seems like it is hardcoded and not remappable.

Thank you for your awesome work!

**Comment by Reonu** [comment] 2024-05-20 17:54
hello! 

this is a duplicate of #41 , very known issue, will be fixed, in the meantime you can use steam input to remap your controller as a workaround

**Closed as completed by Reonu** 2024-05-20 17:54 UTC
